apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
# imageRepository: "docker.io/gcmirrors"
kubernetesVersion: "v1.24.4"
controlPlaneEndpoint: "192.168.57.100:6443"
networking:
  podSubnet: "10.244.0.0/16" # --pod-network-cidr
apiServer:
  certSANs:
  - "192.168.57.100"